# Generated by Django 4.2.7 on 2024-06-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stusent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('age', models.IntegerField()),
                ('institute', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Stusent',
                'verbose_name_plural': 'Stusents',
            },
        ),
    ]
