# Generated by Django 4.2.7 on 2024-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stusent',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
