# Generated by Django 4.2.7 on 2024-06-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_stusent_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stusent',
            new_name='Student',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
